In [1]:
import seaborn as sns

dataset = sns.load_dataset('titanic')

display(dataset.head(2))
dataset.shape

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

(891, 15)

In [2]:
X = dataset.drop('survived', axis = 1)
display(X.head(2))
X.shape

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

(891, 14)

In [ ]:
Y = dataset['survived']
display(Y.head(2))
Y.shape