In [4]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import pandas as pd

dataset = sns.load_dataset('tips')

display(dataset.head(2))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [6]:
enc = LabelEncoder()

dataset['sex'] = enc.fit_transform(dataset['sex'].astype('str'))
dataset['smoker'] = enc.fit_transform(dataset['smoker'].astype('str'))
dataset['day'] = enc.fit_transform(dataset['day'].astype('str'))
dataset['time'] = enc.fit_transform(dataset['time'].astype('str'))

display(dataset.head(3))

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3